version: "3.8"

services:
  app-lms:
    image: bproenca/logs-metrics-spring:latest
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        max_failure_ratio: 0.5
      resources:
         reservations:
           memory: 128M
         limits:
          memory: 256M
    ports:
      - 8080:8080/tcp
    networks:
      - app-network
      - monitor

networks:
  app-network:
    external: true
  monitor:
    external: true