version: '3.8'
services:
  cadvisor:
    image: google/cadvisor:v0.33.0
    deploy:
      mode: global
      resources:
        reservations:
          memory: 50M
        limits:
          memory: 80M
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    # ports:
    #   - 8080:8080
    networks:
      - monitor

  node-exporter:
    image: "prom/node-exporter:v1.2.1"
    pid: host # https://docs.docker.com/compose/compose-file/compose-file-v3/#pid
    volumes:
      - '/:/host:ro,rslave'
    deploy:
      mode: global
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 70M
    command:
      - '--path.rootfs=/host'
    networks:
      - monitor
  
networks:
  monitor:
    external: true
