version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.13.2
    ulimits:
      nofile: 65536
    environment:
      - "xpack.security.enabled=false"
      - "LOGSPOUT=ignore"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - "discovery.type=single-node"
    deploy:
      resources:
        reservations:
          memory: 2048M
        limits:
          memory: 3072M
      placement:
        constraints: [node.role == manager]
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    networks:
      - monitor

  logstash:
    image: logstash:7.13.2
    environment:
      - xpack.security.enabled=false
      - LOGSPOUT=ignore
    deploy:
      resources:
        reservations:
          memory: 384M
        limits:
          memory: 768M
      placement:
        constraints: [node.role == worker]
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        uid: '1000'
        gid: '1000'
        mode: 0664
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - monitor

  kibana:
     image: kibana:7.13.2
     environment:
       - xpack.security.enabled=false
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
       - LOGSPOUT=ignore
     deploy:
       resources:
         reservations:
           memory: 512M
         limits:
           memory: 1024M
       placement:
         constraints: [node.role == worker]
     ports:
        - 5601:5601
     networks:
       - monitor

  logspout:
     image: gliderlabs/logspout:v3.2.3
     environment:
       - SYSLOG_FORMAT=rfc3164
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
     command: syslog://logstash:51415
     deploy:
       mode: global
       resources:
         reservations:
           memory: 20M
         limits:
           memory: 30M
     networks:
      - monitor

networks:
  monitor:
    external: true

configs:
  logstash.conf:
    external: true
