version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.13.2
    ulimits:
      nofile: 65536
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - "discovery.type=single-node"
    deploy:
      resources:
        reservations:
          memory: 1024M
        limits:
          memory: 2048M
      placement:
        constraints: [node.role == manager]
    volumes:
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
    # ports:
    #   - 9200:9200
    networks:
      - monitor

  kibana:
     image: kibana:7.13.2
     environment:
       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     deploy:
       resources:
         reservations:
           memory: 512M
         limits:
           memory: 1024M
       placement:
         constraints: [node.role == worker]
     ports:
        - 5601:5601
     networks:
       - monitor

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.13.2"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro      # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                  # Additional information about containers
      - /data/filebeat/data:/usr/share/filebeat/data:rw               # Persistence data
    user: root                                                        # Allow access to log files and docker.sock
    configs:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    deploy:
      mode: global
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    networks:
      - monitor

networks:
  monitor:
    external: true

configs:
  filebeat.yml:
    external: true
