version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.28.1
    user: "1000:1000"
    environment:
      - LOGSPOUT=ignore
    deploy:
      resources:
        reservations:
          memory: 512M
        limits:
          memory: 1536M
      placement:
        constraints: [node.role == manager]
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /data/prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor

  grafana:
    image: grafana/grafana:8.0.5
    user: "1000:1000"
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 512M
      placement:
        constraints: [node.role == manager]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - LOGSPOUT=ignore
    volumes:
      - /data/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitor

networks:
  monitor:
    external: true

configs:
  prometheus.yml:
    external: true
