version: '3.3'
services:
  prometheus:
    image: prom/prometheus:v1.7.2
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1500M
      placement:
        constraints: [node.role == manager]
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /data/prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor

  grafana:
    image: grafana/grafana:4.5.2
    deploy:
      resources:
        reservations:
          memory: 30M
        limits:
          memory: 200M
      placement:
        constraints: [node.role == manager]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /data/grafana/data:/data/grafana/data
    ports:
      - 3000:3000
    networks:
      - monitor

networks:
  monitor:
    external: true

configs:
  prometheus.yml:
    external: true
