#! /bin/sh
yum update -y
amazon-linux-extras install docker -y
yum install git -y
service docker start
usermod -a -G docker ec2-user
chkconfig docker on
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose